version: '3'

services:
  # a container to serve the blog
  web:
    image: jekyll/jekyll   # build from latest jekyll
    container_name: web
    ports:
      - 4000:4000          # expose this port
    volumes:
      - ./docs:/srv/jekyll      # share local source files with the container
      - ./docs/vendor/bundle:/usr/local/bundle     # cache ruby gems
      
    entrypoint:
      - jekyll
      - serve

# other available entrypoints

#    entrypoint:
#      - bundle
#      - install

#    entrypoint:
#      - jekyll
#      - build
