version: '3.6'

services:
  # a container to serve the blog
  blog:
    build: .
    image: jekyll/jekyll   # build from latest jekyll
    container_name: blog
    ports:
      - 4000:4000          # expose this port
    volumes:
      - .:/srv/jekyll      # share local source files with the container
      - ./vendor/bundle:/usr/local/bundle     # cache ruby gems
      
    entrypoint:
      - jekyll
      - serve

# other available entrypoints

#    entrypoint:
#      - bundle
#      - install

#    entrypoint:
#      - jekyll
#      - build
